name: Python Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11.0
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.0'

      - name: Install Google Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

      - name: Verify Chrome version (optional but helpful)
        run: google-chrome --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt    # ✅ Fixed typo (was `requirement.txt`)

      - name: Run tests and generate HTML report
        run: |
          pytest Testcases/TestAppCard.py --html=reports/test_report.html --self-contained-html
          

      - name: Upload HTML Test Report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-html-report
          path: reports/test_report.html
